#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Student")]
public partial class StudentDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertBook(Book instance);
  partial void UpdateBook(Book instance);
  partial void DeleteBook(Book instance);
  partial void InsertStudent(Student instance);
  partial void UpdateStudent(Student instance);
  partial void DeleteStudent(Student instance);
  #endregion
	
	public StudentDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["StudentConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public StudentDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public StudentDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public StudentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public StudentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Book> Book
	{
		get
		{
			return this.GetTable<Book>();
		}
	}
	
	public System.Data.Linq.Table<Student> Student
	{
		get
		{
			return this.GetTable<Student>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Book")]
public partial class Book : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _BookId;
	
	private System.Nullable<decimal> _BookPrice;
	
	private string _BookAuthor;
	
	private string _BookPublish;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookIdChanging(int value);
    partial void OnBookIdChanged();
    partial void OnBookPriceChanging(System.Nullable<decimal> value);
    partial void OnBookPriceChanged();
    partial void OnBookAuthorChanging(string value);
    partial void OnBookAuthorChanged();
    partial void OnBookPublishChanging(string value);
    partial void OnBookPublishChanged();
    #endregion
	
	public Book()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int BookId
	{
		get
		{
			return this._BookId;
		}
		set
		{
			if ((this._BookId != value))
			{
				this.OnBookIdChanging(value);
				this.SendPropertyChanging();
				this._BookId = value;
				this.SendPropertyChanged("BookId");
				this.OnBookIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookPrice", DbType="Decimal(10,2)")]
	public System.Nullable<decimal> BookPrice
	{
		get
		{
			return this._BookPrice;
		}
		set
		{
			if ((this._BookPrice != value))
			{
				this.OnBookPriceChanging(value);
				this.SendPropertyChanging();
				this._BookPrice = value;
				this.SendPropertyChanged("BookPrice");
				this.OnBookPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookAuthor", DbType="NVarChar(50)")]
	public string BookAuthor
	{
		get
		{
			return this._BookAuthor;
		}
		set
		{
			if ((this._BookAuthor != value))
			{
				this.OnBookAuthorChanging(value);
				this.SendPropertyChanging();
				this._BookAuthor = value;
				this.SendPropertyChanged("BookAuthor");
				this.OnBookAuthorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookPublish", DbType="NVarChar(50)")]
	public string BookPublish
	{
		get
		{
			return this._BookPublish;
		}
		set
		{
			if ((this._BookPublish != value))
			{
				this.OnBookPublishChanging(value);
				this.SendPropertyChanging();
				this._BookPublish = value;
				this.SendPropertyChanged("BookPublish");
				this.OnBookPublishChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _StuId;
	
	private string _StuName;
	
	private string _StuPhone;
	
	private string _BookId;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStuIdChanging(int value);
    partial void OnStuIdChanged();
    partial void OnStuNameChanging(string value);
    partial void OnStuNameChanged();
    partial void OnStuPhoneChanging(string value);
    partial void OnStuPhoneChanged();
    partial void OnBookIdChanging(string value);
    partial void OnBookIdChanged();
    #endregion
	
	public Student()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StuId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int StuId
	{
		get
		{
			return this._StuId;
		}
		set
		{
			if ((this._StuId != value))
			{
				this.OnStuIdChanging(value);
				this.SendPropertyChanging();
				this._StuId = value;
				this.SendPropertyChanged("StuId");
				this.OnStuIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StuName", DbType="NVarChar(20)")]
	public string StuName
	{
		get
		{
			return this._StuName;
		}
		set
		{
			if ((this._StuName != value))
			{
				this.OnStuNameChanging(value);
				this.SendPropertyChanging();
				this._StuName = value;
				this.SendPropertyChanged("StuName");
				this.OnStuNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StuPhone", DbType="NVarChar(40)")]
	public string StuPhone
	{
		get
		{
			return this._StuPhone;
		}
		set
		{
			if ((this._StuPhone != value))
			{
				this.OnStuPhoneChanging(value);
				this.SendPropertyChanging();
				this._StuPhone = value;
				this.SendPropertyChanged("StuPhone");
				this.OnStuPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookId", DbType="NChar(10)")]
	public string BookId
	{
		get
		{
			return this._BookId;
		}
		set
		{
			if ((this._BookId != value))
			{
				this.OnBookIdChanging(value);
				this.SendPropertyChanging();
				this._BookId = value;
				this.SendPropertyChanged("BookId");
				this.OnBookIdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
