<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="SupplierMaster.aspx.cs" Inherits="Admin_SupplierMaster" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphLeft" Runat="Server">
    <a href="CategoryMaster.aspx" style="text-decoration:none">分类管理</a>
  <br />
  <br />
  <a href="SupplierMaster.aspx"  style="text-decoration:none">供应商管理</a>
  <br />
  <br />
  <a href="ProductMaster.aspx"  style="text-decoration:none">商品管理</a>
  <br />
  <br />
  <a href="OrderMaster.aspx"  style="text-decoration:none">订单管理</a>
  <br />
  <br />
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cphRight" Runat="Server">
    <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" DeleteMethod="DeleteCategory" InsertMethod="InSertCategory" SelectMethod="GetAllCategory" TypeName="FoodDElivery" UpdateMethod="UpdateCategory">
    <DeleteParameters>
      <asp:Parameter Name="categoryId" Type="Int32" />
    </DeleteParameters>
    <InsertParameters>
      <asp:Parameter Name="categoryId" Type="Int32" />
      <asp:Parameter Name="name" Type="String" />
      <asp:Parameter Name="descn" Type="String" />
    </InsertParameters>
    <UpdateParameters>
      <asp:Parameter Name="categoryId" Type="Int32" />
      <asp:Parameter Name="name" Type="String" />
      <asp:Parameter Name="descn" Type="String" />
    </UpdateParameters>
  </asp:ObjectDataSource>
  <asp:DetailsView DataSourceID="FoodDelivery" DataKeyNames="SuppId" AutoGenerateRows="False" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateDeleteButton="True"
    AllowPaging="True" ID="DetailsView1" OnItemDeleting="DetailsView1_ItemDeleting"
    runat="server" Width="304px">
    <Fields>
      <asp:BoundField HeaderText="供应商ID" DataField="SuppId" Visible="false" />
      <asp:BoundField HeaderText="供应商名称" DataField="SuppName" />
      <asp:BoundField HeaderText="地址" DataField="Address" />
      <asp:BoundField HeaderText="评分" DataField="Score" />
      <asp:BoundField HeaderText="城市" DataField="City" />
      <asp:BoundField HeaderText="区域" DataField="State" />
      <asp:BoundField HeaderText="手机" DataField="Phone" />
    </Fields>
  </asp:DetailsView>
    <asp:SqlDataSource ID="FoodDelivery" runat="server"></asp:SqlDataSource>
  <asp:Label ID="lblError" runat="server" ForeColor="Red"></asp:Label>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="cphLeft2" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="cphRight2" Runat="Server">
</asp:Content>

