<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Try.aspx.cs" Inherits="Admin_Try" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphLeft" Runat="Server">
    <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" DeleteMethod="DeleteCategory" InsertMethod="InSertCategory" SelectMethod="GetAllCategory" TypeName="MyPetShop.BLL.CategoryService" UpdateMethod="UpdateCategory">
    <DeleteParameters>
      <asp:Parameter Name="categoryId" Type="Int32" />
    </DeleteParameters>
    <InsertParameters>
      <asp:Parameter Name="categoryId" Type="Int32" />
      <asp:Parameter Name="name" Type="String" />
      <asp:Parameter Name="descn" Type="String" />
    </InsertParameters>
    <UpdateParameters>
      <asp:Parameter Name="categoryId" Type="Int32" />
      <asp:Parameter Name="name" Type="String" />
      <asp:Parameter Name="descn" Type="String" />
    </UpdateParameters>
  </asp:ObjectDataSource>
  <asp:DetailsView ID="DetailsView1" runat="server" DataSourceID="ObjectDataSource1" DataKeyNames="CategoryId" AutoGenerateRows="False" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateDeleteButton="True"
    AllowPaging="True"  OnItemDeleting="DetailsView1_ItemDeleting">
    <Fields>
      <asp:BoundField HeaderText="分类ID" DataField="CategoryId" Visible="false" />
      <asp:BoundField HeaderText="分类名称" DataField="CategoryName" />
      <asp:BoundField HeaderText="分类描述" DataField="Descn" />
    </Fields>
  </asp:DetailsView>
      <asp:Label ID="lblError" runat="server" ForeColor="Red"></asp:Label>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cphRight" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="cphLeft2" Runat="Server">
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="cphRight2" Runat="Server">
</asp:Content>

